name: DPO_train
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.0.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py311h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.10.0
      - accelerator==2024.9.13
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - bitsandbytes==0.47.0
      - bottle==0.12.25
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - cut-cross-entropy==25.1.1
      - datasets==3.6.0
      - deepspeed==0.16.4
      - diffusers==0.34.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-transfer==0.1.9
      - hf-xet==1.1.7
      - hjson==3.1.0
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.5
      - ninja==1.11.1.3
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.17.0
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - rich==14.1.0
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - setuptools==80.9.0
      - shtab==1.7.2
      - smmap==5.0.2
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.3.1
      - trl==0.21.0
      - typeguard==4.4.4
      - typing-extensions==4.14.1
      - tyro==0.9.28
      - tzdata==2025.2
      - unsloth==2025.8.4
      - unsloth-zoo==2025.8.3
      - urllib3==2.5.0
      - waitress==3.0.2
      - wandb==0.19.7
      - xformers==0.0.31.post1
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
